#!/usr/bin/env sh

sudo yabai --load-sa
### layout
# bsp or float (default: float)
yabai -m config layout bsp
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding and gaps
yabai -m config top_padding    38
yabai -m config bottom_padding 6
yabai -m config left_padding   6
yabai -m config right_padding  6
yabai -m config window_gap     6

# window appearance
yabai -m config window_border on
yabai -m config active_window_border_color 0xFF89CA78
yabai -m config normal_window_border_color 0xAA000000
yabai -m config window_border_blur on
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.25
yabai -m config active_window_opacity 0.95
yabai -m config normal_window_opacity 0.75

yabai -m rule --add app="^Fig$" border=off # turn border for fig's autosuggest off
yabai -m rule --add app="^Alacritty$" border=off opacity=0.75
yabai -m rule --add app="^kitty$" border=off
yabai -m rule --add app="^FileZilla$" border=off opacity=1
yabai -m rule --add app="^TablePlus$" opacity=1
yabai -m rule --add app="^Arc$" opacity=1
yabai -m rule --add app="^Safari$" opacity=1
# diable Yabai form resizing them.
yabai -m rule --add app="^Finder$" sticky=on manage=off opacity=1
yabai -m rule --add app="^System Information$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Karabiner-Elements$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Raycast$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Homerow$" sticky=on manage=off opacity=1

echo "yabai configuration loaded.."
