#!/usr/bin/env sh

### layout
# bsp or float (default: float)
yabai -m config layout bsp
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding and gaps
yabai -m config top_padding    38
yabai -m config bottom_padding 6
yabai -m config left_padding   6
yabai -m config right_padding  6
yabai -m config window_gap     6

# diable Yabai form resizing them.
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Raycast$" layer=above manage=off
yabai -m rule --add app="^Homerow$" layer=above manage=off

echo "yabai configuration loaded.."
