#!/usr/bin/env sh
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

### layout
# bsp or float (default: float)
yabai -m config layout bsp
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding and gaps
# yabai -m config external_bar all:32:0 # with sketchybar enabled
yabai -m config top_padding 6
yabai -m config bottom_padding 6
yabai -m config left_padding 6
yabai -m config right_padding 6
yabai -m config window_gap 6

# window appearance
# yabai -m config window_border on
# yabai -m config active_window_border_color 0xFF89CA78
# yabai -m config normal_window_border_color 0xAA000000
# yabai -m config window_border_blur on
# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow on

yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.25
yabai -m config active_window_opacity 0.95
yabai -m config normal_window_opacity 0.75

# Mouse settings
# center mouse on window with focus
# yabai -m config mouse_follows_focus on
# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise

yabai -m rule --add app="^Fig$" border=off # turn border for fig's autosuggest off
yabai -m rule --add app="^Alacritty$" border=off opacity=0.75
yabai -m rule --add app="^kitty$" border=off
yabai -m rule --add app="^FileZilla$" border=off opacity=1
yabai -m rule --add app="^TablePlus$" opacity=1
yabai -m rule --add app="^Arc$" opacity=1
yabai -m rule --add app="^Safari$" opacity=1
yabai -m rule --add app="^AnyDesk$" opacity=1
# diable Yabai form resizing them.
yabai -m rule --add app="^Inkdrop$" sticky=on manage=off opacity=1 border=off
yabai -m rule --add app="^Finder$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Minecraft$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Lunar Client$" sticky=on manage=off opacity=1
yabai -m rule --add app="^UTM$" manage=off opacity=1
yabai -m rule --add app="^System Information$" sticky=on manage=off opacity=1
yabai -m rule --add app="^System Settings$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Karabiner-Elements$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Raycast$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Homerow$" sticky=on manage=off opacity=1
yabai -m rule --add app="^Fork$" sticky=on manage=off
yabai -m rule --add app="^LINE$" sticky=on manage=off mouse_follows_focus=off

# This will enable a full refresh of simple-bar on each yabai restart thus allowing it to re-enable it signals.
# osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

echo "yabai configuration loaded.."
