live_config_reload = true

[colors]
# background_opacity = 0.5

[colors.cursor]
cursor = "#ECEFF4"
text = "#3B4252"

[colors.normal]
black = "#4C566A"
blue = "#61afef"
cyan = "#2bbac5"
green = "#89ca78"
magenta = "#d55fde"
red = "#ef596f"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#000000"
foreground = "#abb2bf"

[cursor]
blink_interval = 400
blink_timeout = 5

[cursor.style]
blinking = "Off"

[font]
# ligatures = true
size = 20.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_title = true
dynamic_padding = true
# opacity = 0.85

[window.padding]
x = 2
y = 2
